version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  guacamole:
    image: guacamole/guacamole:latest
    restart: always
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"
    volumes:
      - ./schema:/opt/guacamole/postgresql/schema

  guacd:
    image: guacamole/guacd:latest
    restart: always
    ports:
      - "4822:4822"
