kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-psql-claim
spec:
  storageClassName: local-storage
  volumeName: postgres-sql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: local-storage
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-sql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/wsl/schema
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/wsl/postgres_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - docker-desktop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: postgres-schema
          persistentVolumeClaim:
            claimName: postgres-psql-claim
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: guacamole_db
            - name: POSTGRES_USER
              value: guacamole_user
            - name: POSTGRES_PASSWORD
              value: guacamole_password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-schema
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd:latest
          ports:
            - containerPort: 4822
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-properties-cm
data:
  guacamole.properties: |
    # custom-guacamole.properties
    guacamole-client.max-connections: 100
    guacd-hostname: guacd-service
    guacd-port: 4822
    guacd-encryption: websocket
    enable-websocket: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      volumes:
        - name: guacamole-properties-volume
          configMap:
            name: guacamole-properties-cm
            items:
              - key: guacamole.properties
                path: guacamole.properties
      containers:
        - name: guacamole
          image: guacamole/guacamole:latest
          env:
            - name: GUACD_HOSTNAME
              value: guacd-service
            - name: POSTGRES_HOSTNAME
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: guacamole_db
            - name: POSTGRES_USER
              value: guacamole_user
            - name: POSTGRES_PASSWORD
              value: guacamole_password
            - name: POSTGRES_DRIVER
              value: org.postgresql.Driver
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: guacamole-properties-volume
              mountPath: /home/etc/guacamole.properties
              subPath: guacamole.properties
---
apiVersion: v1
kind: Service
metadata:
  name: guacd-service
spec:
  type: LoadBalancer
  selector:
    app: guacd
  ports:
    - protocol: TCP
      port: 4822
      targetPort: 4822
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
spec:
  type: LoadBalancer
  selector:
    app: guacamole
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
