apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-socket-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-socket-test
  template:
    metadata:
      labels:
        app: web-socket-test
    spec:
      containers:
        - name: web-socket-test
          image: ksdn117/web-socket-test
          ports:
            - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: web-socket-test-service
spec:
  type: LoadBalancer
  selector:
    app: web-socket-test
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010